"""initial migration

Revision ID: 023421e371f2
Revises: 
Create Date: 2024-07-04 22:44:01.060392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023421e371f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('likes')
        batch_op.drop_column('jobs')

    # ### end Alembic commands ###
