from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c4c1cd17db4'
down_revision = '8e9679cdc10f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('photos',
            existing_type=sa.VARCHAR(),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=True,
            postgresql_using='photos::json'
        )
        batch_op.add_column(sa.Column('videos', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('photos',
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=sa.VARCHAR(),
            existing_nullable=True,
            postgresql_using='photos::text'
        )
        batch_op.drop_column('videos')

    # ### end Alembic commands ###
