"""added columns for photos and videos

Revision ID: 8e9679cdc10f
Revises: f86c872fbb8a
Create Date: 2024-07-09 20:33:11.813570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9679cdc10f'
down_revision = 'f86c872fbb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('video')
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
