"""changed photos and videos types to json

Revision ID: b929691935a0
Revises: ed8a71c23871
Create Date: 2024-07-11 19:37:20.172014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b929691935a0'
down_revision = 'ed8a71c23871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_filename')
        batch_op.drop_column('video')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
